# Generated by Django 5.0.4 on 2024-04-06 21:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiles', models.CharField(choices=[('first', 'First Choice'), ('second', 'Second Choice'), ('third', 'Third Choice')], max_length=20)),
                ('name', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', error_messages={'unique': 'This username is already taken.'}, max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(default='', error_messages={'unique': 'This email is already taken.'}, max_length=255, unique=True)),
                ('password', models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(7)])),
                ('agree_to_terms', models.BooleanField(default=False, error_messages={'required': 'You must agree to the terms.'})),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('location', models.CharField(default='', max_length=1000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
