# Generated by Django 5.0.4 on 2024-04-06 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userregistration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='agree_to_terms',
            field=models.BooleanField(default=False, error_messages={'required': 'You must agree to the terms.'}),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(default='', error_messages={'unique': 'This email is already taken.'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(default='', max_length=255, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='username',
            field=models.CharField(default='', error_messages={'unique': 'This username is already taken.'}, max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
